# Generated by Django 5.2 on 2025-05-25 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("buying_price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("stock", models.IntegerField()),
                ("image", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="api.category",
                    ),
                ),
            ],
        ),
    ]
